services:
  - type: web
    name: loteria-drabba
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: N8N_URL
        value: https://erythrocytic-faustina-breathily.ngrok-free.dev
